## NORMALIZATION

## normalization is a techinique often applied as part of data preapration for machine learning .The goal of normalization is to change values of numeric columns in dataset to use a common scale , without distorting differences in the range of values or losing information 

* it is always said that we must remove units in numeric columns and bring them in one scale

## min max scaling 
## mean normalization 
## max absolute 
## robust scaling

# MINMax scaling - (intution)

* Xi' = Xi-Xmin/Xmax-Xmin
* iski range [0,1] hogi bcx Xi=Xmin then Xi'=0
* if Xi=Xmax then Xi'=0 so its value will remain in the region [0,1]

In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

Bad value in file WindowsPath('C:/Users/acer/anaconda3/Lib/site-packages/matplotlib/mpl-data/stylelib/classic.mplstyle'), line 162 ('mathtext.default: normal  # The default font to use for math.'): Key mathtext.default: 'normal' is not a valid value for mathtext.default; supported values are ['rm', 'cal', 'bfit', 'it', 'tt', 'sf', 'bf', 'default', 'bb', 'frak', 'scr', 'regular']

Bad key axes3d.depthshade in file C:\Users\acer\anaconda3\Lib\site-packages\matplotlib\mpl-data\stylelib\classic.mplstyle, line 225 ('axes3d.depthshade   : False   # depth shade for 3D scatter plots')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.10.0/lib/matplotlib/mpl-data/matplotlibrc
or from the matplotlib source distribution

Bad key axes3d.depthshade_minalpha in file C:\Users\acer\anaconda3\Lib\site-packages\matplotlib\mpl-data\stylelib\classic.mplstyle, line 226 ('axes3d.depthshade_minalpha : 0.3  # minimum alpha value for depth shading')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.10.0/lib/matplotlib/mpl-data/matplotlibrc
or from the matplotlib source distribution
Bad value in file WindowsPath('C:/Users/acer/anaconda3/Lib/site-packages/matplotlib/mpl-data/stylelib/_classic_test_patch.mplstyle'), line 6 ('hatch.color: edge'): Key hatch.color: 'edge' does not look like a color arg

In [2]:
df=pd.read_csv('wine_data.csv', usecols=[0,1,2])
df.columns=['class label','Alcohol','malic acid']

In [3]:
df

     class label  Alcohol  malic acid
0              1    13.20        1.78
1              1    13.16        2.36
2              1    14.37        1.95
3              1    13.24        2.59
4              1    14.20        1.76
..           ...      ...         ...
172            3    13.71        5.65
173            3    13.40        3.91
174            3    13.27        4.28
175            3    13.17        2.59
176            3    14.13        4.10

[177 rows x 3 columns]

In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test= train_test_split(df.drop('class label',axis=1),df['class label'],test_size=0.3,random_state=0)

In [5]:
X_train.shape ,X_test.shape

((123, 2), (54, 2))

In [6]:
from sklearn.preprocessing import MinMaxScaler

In [7]:
scaler=MinMaxScaler()
scaler.fit(X_train)
X_train_scaled=scaler.transform(X_train)
X_test_scaled=scaler.transform(X_test)  #sickit learn ki library use karte hai toh woh dataframe ko numpy arrays me change kar deta hai

In [8]:
X_train_scaled=pd.DataFrame(X_train_scaled,columns=X_train.columns)
X_test_scaled=pd.DataFrame(X_test_scaled,columns=X_test.columns)

np.round(X_train.describe(),1)

In [10]:
np.round(X_train_scaled.describe(),1)

       Alcohol  malic acid
count    123.0       123.0
mean       0.5         0.3
std        0.2         0.2
min        0.0         0.0
25%        0.4         0.1
50%        0.5         0.2
75%        0.7         0.4
max        1.0         1.0

# MEAN NORMALIZATION

* Xi'= xi-xmean/Xmax-Xmin
* data is mean centered
* range is from [-1 1]
* -ve value means less than mean
* positive value means greater than mean
* rarely used no class in sckit learn

# Max absolute scaling

* xi' = xi/|xmax|
* class in sckit learn as named maxabsscaled
* kisi bhi data me agar zeros zyada hai tab ye method use hota hai

# Robust scaling

* xi' = xi - xmedian/ interquartilerange(75th percentile - 25 percentile}
*  it is robust to outlier

# Normalization vs standardization

* first ask question if feature scaling is rquired
* min max scaler is mostly used jab hume pata hota hai ki minimum aur maximum values ek box me rhegi