# -DAY4 WORKING WITH JSON/SQL

In [6]:
import pandas as pd
import json

In [2]:
df=pd.read_json("ipl.json")

In [3]:
with open("ipl.json") as f:
    data=json.load(f)
df1=pd.json_normalize(df['data'])
df1.head()

,innings,meta.data_version,meta.created,meta.revision,info.balls_per_over,info.city,info.dates,info.event.name,info.event.match_number,info.gender,...,info.registry.people.F Gomes,info.registry.people.Monu Kumar,info.registry.people.MR Singh,info.registry.people.DAJ Bracewell,info.registry.people.IC Porel,info.registry.people.RV Pawar,info.registry.people.T Mishra,info.registry.people.Gurnoor Brar,info.registry.people.KS Sharma,info.registry.people.S Midhun
0,"[{'team': 'Chennai Super Kings', 'overs': [{'o...",1.1.0,2023-04-26,1,6,Kolkata,[2023-04-23],Indian Premier League,33.0,male,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"[{'team': 'Rajasthan Royals', 'overs': [{'over...",1.0.0,2011-05-02,2,6,Kimberley,[2009-05-09],Indian Premier League,37.0,male,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"[{'team': 'Mumbai Indians', 'overs': [{'over':...",1.1.0,2021-10-02,2,6,Sharjah,[2021-10-02],Indian Premier League,46.0,male,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"[{'team': 'Mumbai Indians', 'overs': [{'over':...",1.0.0,2015-05-19,1,6,Mumbai,[2015-05-19],Indian Premier League,NaN,male,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"[{'team': 'Delhi Daredevils', 'overs': [{'over...",1.0.0,2011-05-06,3,6,Delhi,[2008-05-17],Indian Premier League,40.0,male,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## working with json files

In [2]:
!pip install mysql.connector

Requirement already satisfied: mysql.connector in c:\users\acer\anaconda3\lib\site-packages (2.2.9)

WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\acer\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\acer\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\acer\anaconda3\Lib\site-packages)

In [3]:
import mysql.connector

In [5]:
conn=mysql.connector.connect(host='localhost',user='root',password='',database='world')

In [9]:
df=pd.read_sql_query("SELECT * FROM city",conn) #matlab select all from city

C:\Users\acer\AppData\Local\Temp\ipykernel_19024\4114825647.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql_query("SELECT * FROM city",conn) #matlab select all from city

In [10]:
df

        ID            Name CountryCode       District  Population
0        1           Kabul         AFG          Kabol     1780000
1        2        Qandahar         AFG       Qandahar      237500
2        3           Herat         AFG          Herat      186800
3        4  Mazar-e-Sharif         AFG          Balkh      127800
4        5       Amsterdam         NLD  Noord-Holland      731200
...    ...             ...         ...            ...         ...
4074  4075      Khan Yunis         PSE     Khan Yunis      123175
4075  4076          Hebron         PSE         Hebron      119401
4076  4077        Jabaliya         PSE     North Gaza      113901
4077  4078          Nablus         PSE         Nablus      100231
4078  4079           Rafah         PSE          Rafah       92020

[4079 rows x 5 columns]